cleanup, remove old autosupport script and show drive examples as 'sda'
git-svn-id: https://svn.code.sf.net/p/astlinux/code/branches/1.0@5334 57edc7d3-a90e-0410-b364-91459a37fc5a

diff --git a/project/astlinux/target_skeleton/etc/rc b/project/astlinux/target_skeleton/etc/rc
--- a/project/astlinux/target_skeleton/etc/rc
+++ b/project/astlinux/target_skeleton/etc/rc
@@ -284,7 +284,7 @@ none    /var            tmpfs   size=5000k      0       0
           echo "Runnix vfat partition re-mounted read-only" 
         fi                                                  
       else                                                  
-        echo "Runnix vfat partition label not found, use: dosfslabel /dev/hda1 RUNNIX" 1>&2
+        echo "Runnix vfat partition label not found, use: dosfslabel /dev/sda1 RUNNIX" 1>&2
       fi                                                                                   
     fi                                                                                     
   fi                                                                                       
