Add virtio-blk block device system support System wide: runnix, runnix-iso, initrd, and astlinux Enable CONFIG_VIRTIO_BLK=y in the kernels, and support booting off of /dev/vd[a-d]
Tested via Proxmox and Vultr (hosted).

Note:  The virtblk block device is dynamically allocated starting at 254 and
decreasing until an unused block device index is found.

With these kernel configs enabled: (devtmpfs)
--
CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
--
The /dev/vd* block devices are automatically created to match the dynamic index,
as is the case for the astlinux image.

For runnix and runnix-iso, we currently don't enable devtmpfs, and no loadable modules,
so everything is built-in to the kernel core.  As such we use device_table_dev.txt to
statically assign virtblk to index 254.

If runnix and runnix-iso ever supported multiple dynamically assigned block devices, it
may be worth looking at enabling devtmpfs.

diff --git a/project/astlinux/target_skeleton/etc/rc b/project/astlinux/target_skeleton/etc/rc
--- a/project/astlinux/target_skeleton/etc/rc
+++ b/project/astlinux/target_skeleton/etc/rc
@@ -47,6 +47,34 @@ ast_checkfs () {
   esac
 }
 
+set_kddev () {
+
+  case $KDDEV in
+
+  # valid device name -- should we test for the device being present?
+  /dev/[sv]d[a-h][0-9])
+    ;;
+
+  # not set
+  '')
+    ;;
+
+  auto)
+    if [ -x /sbin/findfs ]; then
+      KDDEV=`/sbin/findfs LABEL=ASTKD 2>/dev/null`
+    else
+      echo "Keydisk set to 'auto' but no matching disk label found." >&2
+    fi
+    ;;
+
+  # gibberish...
+  *)
+    echo "Invalid keydisk name: $KDDEV" >&2
+    exec /bin/sh
+    ;;
+  esac
+}
+
 init() {
 
   mount -t proc none /proc
@@ -94,31 +122,6 @@ init() {
     esac
 
   done
-
-  case $KDDEV in
-
-  # valid device name -- should we test for the device being present?
-  /dev/[sh]d[a-h][0-9])
-    ;;
-
-  # not set
-  '')
-    ;;
-
-  auto)
-    if [ -x /sbin/findfs ]; then
-      KDDEV=`/sbin/findfs LABEL=ASTKD 2>/dev/null`
-    else
-      echo "Keydisk set to 'auto' but no matching disk label found." >&2
-    fi
-    ;;
-
-  # gibberish...
-  *)
-    echo "Invalid keydisk name: $KDDEV" >&2
-    exec /bin/sh
-    ;;
-  esac
 
   devtmpfs="$(awk '/^devtmpfs/ { print $2; nextfile; }' /proc/mounts)"
   if [ -n "$devtmpfs" ]; then
@@ -168,6 +171,8 @@ $fstab_tmp
 $fstab_var
 $fstab_shm
 " > /tmp/etc/fstab
+
+  set_kddev
 
   mkdir /var/spool /var/lib
   mkdir /var/empty /var/lock /var/db /var/run /var/racoon
@@ -255,7 +260,7 @@ $fstab_shm
         echo "Error: $IOS is not available on $IODEV"
       fi
     done
-  fi 
+  fi
 
   #Check and mount filesystems
   if [ -z "$ASTIMG" ]; then
@@ -292,19 +297,19 @@ $fstab_shm
     fi
   fi
 
-  # Re-mount Runnix partition                                    
-  if ! mount | grep -q "/oldroot/cdrom"; then                   
-    if [ -x /sbin/findfs ]; then                         
-      LABEL=`/sbin/findfs LABEL=RUNNIX`                                 
-      if [ -n "$LABEL" ]; then                                
+  # Re-mount Runnix partition
+  if ! mount | grep -q "/oldroot/cdrom"; then
+    if [ -x /sbin/findfs ]; then
+      LABEL=`/sbin/findfs LABEL=RUNNIX`
+      if [ -n "$LABEL" ]; then
         if mount -t vfat -o ro "$LABEL" /oldroot/cdrom; then
-          echo "Runnix vfat partition re-mounted read-only" 
-        fi                                                  
-      else                                                  
+          echo "Runnix vfat partition re-mounted read-only"
+        fi
+      else
         echo "Runnix vfat partition label not found, use: dosfslabel /dev/sda1 RUNNIX" 1>&2
-      fi                                                                                   
-    fi                                                                                     
-  fi                                                                                       
+      fi
+    fi
+  fi
 
   # Check for video (non-serial) console, and load os/console.kmap if it exists
   if ! echo "$CMDLINE" | grep -q "console="; then
