openvpn, server and client init.d scripts, return an error num if openvpn fails to start, additionally for the server create '/mnt/kd/openvpn/ccd' by default if it does not exist
git-svn-id: https://svn.code.sf.net/p/astlinux/code/branches/1.0@5959 57edc7d3-a90e-0410-b364-91459a37fc5a

diff --git a/package/openvpn/openvpn.init b/package/openvpn/openvpn.init
--- a/package/openvpn/openvpn.init
+++ b/package/openvpn/openvpn.init
@@ -34,10 +34,13 @@ init () {
   if [ -d /mnt/kd/openvpn ]; then
     ln -snf /mnt/kd/openvpn /tmp/etc/openvpn
   else
-    echo "No openvpn certificate directory found.
-A directory on the keydisk is required.
-Manual configuration of certificates is also required."
-    exit
+    echo "openvpn: Directory \"/mnt/kd/openvpn\" not found, exiting." >&2
+    exit 1
+  fi
+
+  # Create the 'ccd' directory by default
+  if [ ! -d /mnt/kd/openvpn/ccd ]; then
+    mkdir /mnt/kd/openvpn/ccd
   fi
 
   if [ -f /mnt/kd/openvpn/openvpn.conf ]; then
@@ -137,9 +140,12 @@ start () {
   if  [ -f /etc/openvpn.conf ]; then
     echo "Starting OpenVPN Server..."
     openvpn --daemon  --writepid $pid --config /etc/openvpn.conf
-    if [ $? = 0 ]; then
-      touch $lock
+    result=$?
+    if [ $result -ne 0 ]; then
+      echo "openvpn: Failed to start." >&2
+      return $result
     fi
+    touch $lock
   fi
 }
 
diff --git a/package/openvpn/openvpnclient.init b/package/openvpn/openvpnclient.init
--- a/package/openvpn/openvpnclient.init
+++ b/package/openvpn/openvpnclient.init
@@ -34,10 +34,8 @@ init () {
   if [ -d /mnt/kd/openvpn ]; then
     ln -snf /mnt/kd/openvpn /tmp/etc/openvpn
   else
-    echo "No openvpn certificate directory found.
-A directory on the keydisk is required.
-Manual configuration of certificates is also required."
-    exit
+    echo "openvpnclient: Directory \"/mnt/kd/openvpn\" not found, exiting." >&2
+    exit 1
   fi
 
   if [ -f /mnt/kd/openvpn/openvpnclient.conf ]; then
@@ -103,9 +101,12 @@ start () {
   if  [ -f /etc/openvpnclient.conf ]; then
     echo "Starting OpenVPN Client..."
     openvpn --daemon  --writepid $pid --config /etc/openvpnclient.conf
-    if [ $? = 0 ]; then
-      touch $lock
+    result=$?
+    if [ $result -ne 0 ]; then
+      echo "openvpnclient: Failed to start." >&2
+      return $result
     fi
+    touch $lock
   fi
 }
 
