strongswan, add AIF support for 'ipsec' VPN type, keep both racoon and strongswan from running at the same time
git-svn-id: https://svn.code.sf.net/p/astlinux/code/branches/1.0@7956 57edc7d3-a90e-0410-b364-91459a37fc5a

diff --git a/package/strongswan/ipsec.init b/package/strongswan/ipsec.init
--- a/package/strongswan/ipsec.init
+++ b/package/strongswan/ipsec.init
@@ -6,8 +6,8 @@
 
 PIDFILE="/var/run/charon.pid"
 
-init () {
-
+init ()
+{
   if ! SYS_is_vpn_type ipsec; then
     exit
   fi
@@ -33,6 +33,15 @@ init () {
 start ()
 {
   if SYS_is_vpn_type ipsec; then
+    if SYS_is_vpn_type racoon || SYS_is_vpn_type ipsecmobile; then
+      echo "Failed starting strongSwan IPsec, racoon IPsec is also enabled." >&2
+      exit 1
+    fi
+
+    ## Stop racoon IPsec if it is running
+    if [ -f /etc/init.d/racoon -a -f /var/run/racoon.pid ]; then
+      service racoon stop
+    fi
 
     /usr/sbin/ipsec start >/dev/null
   fi
