runnix-iso, installer-menu, if zero-ing first 1 GB fails, allow a choice to continue.  Possible with thin clients and small built-in DOM's or 1 GB CF cards
git-svn-id: https://svn.code.sf.net/p/astlinux/code/branches/1.0@7508 57edc7d3-a90e-0410-b364-91459a37fc5a

diff --git a/project/runnix-iso/target_skeleton/sbin/installer-menu b/project/runnix-iso/target_skeleton/sbin/installer-menu
--- a/project/runnix-iso/target_skeleton/sbin/installer-menu
+++ b/project/runnix-iso/target_skeleton/sbin/installer-menu
@@ -121,8 +121,16 @@ install_disk()
 
   dd if=/dev/zero of=$disk bs=64k count=16000 >/dev/null 2>/dev/null
   if [ $? -ne 0 ]; then
-    display_msg "Error zero'ing first 1 GB.\nInstall failed !"
-    return 1
+    dialog \
+      --clear \
+      --backtitle "$BACKTITLE" \
+      --title "[ Error Erasing ]" \
+      --yesno "Error zero'ing first 1 GB.\nContinue anyway ?" 6 60
+  
+    if [ $? -ne 0 ]; then
+      display_msg "Error zero'ing first 1 GB.\nInstall failed !"
+      return 1
+    fi
   fi
 
   display_progress "Step 3 of 3: Writing AstLinux Image to '$disk'\nThis may take a long time..."
