add './scripts/master-build' script, to build images for all boards
git-svn-id: https://svn.code.sf.net/p/astlinux/code/branches/1.0@5202 57edc7d3-a90e-0410-b364-91459a37fc5a

diff --git a/scripts/astlinux-makeimage b/scripts/astlinux-makeimage
--- a/scripts/astlinux-makeimage
+++ b/scripts/astlinux-makeimage
@@ -13,20 +13,6 @@ RUNNIX_DIR="output/build/runnix-${RUNNIX_VER// /}"
 
 RUNFS_DIR="output/build/runfs"
 
-make_release_version()
-{
-  ASTURL="$(LANG=C svn info | awk -F': ' '/^URL:/ { print $2 }')"
-  ASTBASE="$(basename ${ASTURL})"
-  ASTREV="$(LANG=C svn info | awk -F': ' '/^Last Changed Rev:/ { print $2 }')"
-  ASTEXTRA=""
-
-  if [ "$(cat "project/astlinux/target_skeleton/etc/astlinux-release")" = "svn" ]; then
-    ASTVER="astlinux-${ASTBASE}-${ASTREV}${ASTEXTRA}"
-  else
-    ASTVER="$(cat "project/astlinux/target_skeleton/etc/astlinux-release")${ASTEXTRA}"
-  fi
-}
-
 #
 # put whatever edits you need to make to the VFAT filesystem here.
 #
@@ -39,8 +25,6 @@ editConf()
 
   return 0
 }
-
-make_release_version
 
 ASTRW_FORMAT=
 BOOT_ONLY=
@@ -94,6 +78,13 @@ fi
 
 if [ ! -d $RUNNIX_DIR ] || [ ! -d $RUNFS_DIR ]; then
   echo "astlinux-makeimage: This image wasn't built with RUNNIX enabled." >&2
+  exit 1
+fi
+
+ASTVER="$(cat ${RUNFS_DIR}/os/ver)"
+
+if [ -z "$ASTVER" ]; then
+  echo "astlinux-makeimage: missing runfs version file." >&2
   exit 1
 fi
 
