kernel-minor-version-bump, for 'make oldconfig' specify toolchain CC= and LD= CONFIG_CC_VERSION_TEXT (etc.) is changed to match the toolchain rather than the host

diff --git a/scripts/kernel-minor-version-bump b/scripts/kernel-minor-version-bump
--- a/scripts/kernel-minor-version-bump
+++ b/scripts/kernel-minor-version-bump
@@ -28,6 +28,13 @@ if [ $2 -le $1 ]; then
   exit 1
 fi
 
+TOOLCHAIN_CC="$(pwd)/output/host/usr/bin/x86_64-unknown-linux-gnu-gcc"
+TOOLCHAIN_LD="$(pwd)/output/host/usr/bin/x86_64-unknown-linux-gnu-ld"
+if [ ! -x "$TOOLCHAIN_CC" ] || [ ! -x "$TOOLCHAIN_LD" ]; then
+  echo "$0: Toolchain gcc/ld path not found"
+  exit 1
+fi
+
 error_restore_exit()
 {
   mv .config.save .config
@@ -75,7 +82,7 @@ for linux in $LINUX64_CONFIGS; do
   (
     cd output/build/linux-custom/
     cp "../../../$linux" .config
-    ARCH=x86_64 make oldconfig
+    ARCH=x86_64 make oldconfig CC="${TOOLCHAIN_CC}" LD="${TOOLCHAIN_LD}"
     echo "========"
     diff -u "../../../$linux" .config
     echo "========"
