fossil, helper script improvements
git-svn-id: https://svn.code.sf.net/p/astlinux/code/branches/1.0@7203 57edc7d3-a90e-0410-b364-91459a37fc5a

diff --git a/package/fossil/scripts/fossil-open b/package/fossil/scripts/fossil-open
--- a/package/fossil/scripts/fossil-open
+++ b/package/fossil/scripts/fossil-open
@@ -1,6 +1,15 @@
 #!/bin/sh
 
-cd /mnt/kd
+REPO="/mnt/kd/fossil/astlinux.fossil"
 
-fossil open /mnt/kd/fossil/astlinux.fossil --keep >/dev/null
+if [ ! -f $REPO ]; then
+  echo "Fossil repository not found: $REPO" >&2
+  exit 1
+fi
+
+if ! cd /mnt/kd; then
+  exit 1
+fi
+
+fossil open $REPO --keep >/dev/null
 fossil status
diff --git a/package/fossil/scripts/fossil-update b/package/fossil/scripts/fossil-update
--- a/package/fossil/scripts/fossil-update
+++ b/package/fossil/scripts/fossil-update
@@ -4,9 +4,31 @@ export FOSSIL_HOME="/mnt/kd/fossil"
 
 message="${1:-auto commit via cron}"
 
-cd /mnt/kd
+REPO="/mnt/kd/fossil/astlinux.fossil"
 
-fossil open /mnt/kd/fossil/astlinux.fossil --keep >/dev/null
+if [ ! -f $REPO ]; then
+  echo "Fossil repository not found: $REPO" >&2
+  exit 1
+fi
+
+if ! cd /mnt/kd; then
+  exit 1
+fi
+
+fossil open $REPO --keep >/dev/null
 fossil status
+
+## Check for locally added files, add them to the repo
+fossil ls | sed 's:/.*$::' | sort | uniq | xargs fossil add --force
+
+## Check for locally deleted files, remove them from the repo
+if fossil changes | grep -q '^MISSING'; then
+  fossil changes | awk '/^MISSING/ { print $2; }' | xargs fossil forget
+fi
+
 fossil commit --no-warnings -m "$message"
+rtn=$?
+
 fossil close --force
+
+exit $rtn
